### ISSUE TITLE
Test-issue

### ISSUE THREAD

**Issue by ramesh2051** [Ramesh-playground/githubtechnical#2]
```[tasklist]
### Tasks
- [ ] Change the logo
- [ ] Change the color
- [ ] https://github.com/Ramesh-playground/githubtechnical/issues/3
- [ ] 
```
